# Generated by Django 5.2.7 on 2025-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100, verbose_name="Язык")),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Начальный"),
                            ("A2", "A2 - Элементарный"),
                            ("B1", "B1 - Средний"),
                            ("B2", "B2 - Выше среднего"),
                            ("C1", "C1 - Продвинутый"),
                            ("C2", "C2 - Владение в совершенстве"),
                            ("native", "Родной"),
                        ],
                        max_length=10,
                        verbose_name="Уровень владения",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ["order"],
            },
        ),
    ]
