# Generated by Django 5.2.7 on 2025-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="Адрес"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                ("summary", models.TextField(blank=True, verbose_name="О себе")),
            ],
            options={
                "verbose_name": "Личная информация",
                "verbose_name_plural": "Личная информация",
            },
        ),
    ]
