# Generated by Django 5.2.7 on 2025-11-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="resume.resume",
                verbose_name="Резюме",
            ),
        ),
    ]
