# Generated by Django 5.2.7 on 2025-11-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resume", "0001_initial"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumes",
                to="template.template",
                verbose_name="Шаблон",
            ),
        ),
    ]
