# Generated by Django 5.2.7 on 2025-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
