# Generated by Django 5.2.7 on 2025-11-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название навыка"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начальный"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                            ("expert", "Эксперт"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Технические"),
                            ("soft", "Гибкие навыки"),
                            ("language", "Языки"),
                            ("other", "Другое"),
                        ],
                        default="technical",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["order", "name"],
            },
        ),
    ]
